# Etapa 1: Usar uma imagem base oficial do Python
FROM python:3.10-slim

# Definir o diretório de trabalho na imagem
WORKDIR /app

# Instalar o Pipenv para gerenciar as dependências
RUN pip install pipenv

# Copiar o Pipfile e o Pipfile.lock para o container
COPY Pipfile Pipfile.lock /app/

# Instalar as dependências do projeto
RUN pipenv install --system --deploy

# Copiar toda a estrutura do projeto para o container
COPY . /app

# Expor a porta padrão do FastAPI
EXPOSE 8000

# Configurar as variáveis de ambiente do arquivo .env
ENV PYTHONUNBUFFERED=1
ENV ENV_FILE_LOCATION=/app/.env

# Comando para iniciar o servidor FastAPI usando Uvicorn
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
